name: pawplan
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.0
  qr_flutter: ^4.1.0
  flutter_local_notifications: 16.3.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  table_calendar: ^3.1.2
  provider: ^6.1.2
  android_intent_plus: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

android:
  permissions:
    - android.permission.CAMERA
    - android.permission.WRITE_EXTERNAL_STORAGE

