// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpsMx4Z_D0aHOTkuW_anH5hhF8gcF7cqA',
    appId: '1:611625177639:web:a7d3f2eb0c35db5a6f3402',
    messagingSenderId: '611625177639',
    projectId: 'pawplan-ebdc8',
    authDomain: 'pawplan-ebdc8.firebaseapp.com',
    storageBucket: 'pawplan-ebdc8.firebasestorage.app',
    measurementId: 'G-84JF7793ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IhQqEFcYAwvHlsHZp5g0NIpRGvRZYJM',
    appId: '1:611625177639:android:ac0c0ba44b2850d26f3402',
    messagingSenderId: '611625177639',
    projectId: 'pawplan-ebdc8',
    storageBucket: 'pawplan-ebdc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYUZQ8kB1fAa3jUoy9ExO_nZRaRtc1iwo',
    appId: '1:611625177639:ios:771fba4a7ec2135b6f3402',
    messagingSenderId: '611625177639',
    projectId: 'pawplan-ebdc8',
    storageBucket: 'pawplan-ebdc8.firebasestorage.app',
    iosClientId: '611625177639-ndvudvi8o2jngfve7rbet4a5s6osiujg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYUZQ8kB1fAa3jUoy9ExO_nZRaRtc1iwo',
    appId: '1:611625177639:ios:771fba4a7ec2135b6f3402',
    messagingSenderId: '611625177639',
    projectId: 'pawplan-ebdc8',
    storageBucket: 'pawplan-ebdc8.firebasestorage.app',
    iosClientId: '611625177639-ndvudvi8o2jngfve7rbet4a5s6osiujg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpsMx4Z_D0aHOTkuW_anH5hhF8gcF7cqA',
    appId: '1:611625177639:web:fab654e06f8376f46f3402',
    messagingSenderId: '611625177639',
    projectId: 'pawplan-ebdc8',
    authDomain: 'pawplan-ebdc8.firebaseapp.com',
    storageBucket: 'pawplan-ebdc8.firebasestorage.app',
    measurementId: 'G-8G9GSZDP94',
  );
}
